window.BEER_DB = [
  {
    "id": "BEER_001",
    "nameKo": "하이네켄 오리지널",
    "nameEn": "Heineken Original",
    "brewery": "Heineken",
    "country": "네덜란드",
    "styleMajor": "청량 라거",
    "styleMinor": "International Pale Lager",
    "abv": 5,
    "ibu": 23,
    "bitterness": 2,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 2,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "grain, herbal, light fruit",
    "flavorSummary": "깔끔함, 대중적, 산뜻함",
    "foodTags": "치킨, 감자튀김, 피자",
    "occasionTags": "가벼운 모임, 퇴근 후",
    "natalTags": "편안함, 사교적, 무난함",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 1,
    "natalSensory": 1,
    "natalSocial": 5,
    "natalAdventure": 1,
    "natalTone": "편안함·사교적"
  },
  {
    "id": "BEER_002",
    "nameKo": "스텔라 아르투아",
    "nameEn": "Stella Artois",
    "brewery": "Stella Artois",
    "country": "벨기에",
    "styleMajor": "청량 라거",
    "styleMinor": "International Pale Lager",
    "abv": 5,
    "ibu": 24,
    "bitterness": 2,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 2,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "grain, floral, herbal",
    "flavorSummary": "드라이, 깔끔함, 가벼운 홉",
    "foodTags": "피자, 튀김, 샌드위치",
    "occasionTags": "모임, 식사 반주",
    "natalTags": "세련됨, 균형, 사교적",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 2,
    "natalSocial": 5,
    "natalAdventure": 1,
    "natalTone": "세련됨·균형"
  },
  {
    "id": "BEER_003",
    "nameKo": "아사히 슈퍼 드라이",
    "nameEn": "Asahi Super Dry",
    "brewery": "Asahi",
    "country": "일본",
    "styleMajor": "청량 라거",
    "styleMinor": "Japanese Dry Lager",
    "abv": 5,
    "ibu": 20,
    "bitterness": 2,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 1,
    "body": 1,
    "carbonation": 5,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "rice, grain, faint hop",
    "flavorSummary": "매우 드라이, 가벼움",
    "foodTags": "회, 튀김, 야키토리",
    "occasionTags": "퇴근 후, 식사 반주",
    "natalTags": "절제, 속도감, 깔끔함",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 1,
    "natalSocial": 4,
    "natalAdventure": 1,
    "natalTone": "절제·명료함"
  },
  {
    "id": "BEER_004",
    "nameKo": "코로나 엑스트라",
    "nameEn": "Corona Extra",
    "brewery": "Grupo Modelo",
    "country": "멕시코",
    "styleMajor": "청량 라거",
    "styleMinor": "International Pale Lager",
    "abv": 4.5,
    "ibu": 18,
    "bitterness": 1,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 1,
    "body": 1,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "grain, light citrus",
    "flavorSummary": "가벼움, 담백함",
    "foodTags": "타코, 나초, 해산물",
    "occasionTags": "야외, 파티",
    "natalTags": "느긋함, 햇살, 개방적",
    "availability": "A",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 1,
    "natalSensory": 2,
    "natalSocial": 5,
    "natalAdventure": 1,
    "natalTone": "자유·느긋함"
  },
  {
    "id": "BEER_005",
    "nameKo": "칭따오 라거",
    "nameEn": "Tsingtao Lager",
    "brewery": "Tsingtao Brewery",
    "country": "중국",
    "styleMajor": "청량 라거",
    "styleMinor": "International Pale Lager",
    "abv": 4.7,
    "ibu": 20,
    "bitterness": 2,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 2,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "grain, light floral",
    "flavorSummary": "고소함, 산뜻함",
    "foodTags": "중식, 양꼬치, 튀김",
    "occasionTags": "회식, 식사 반주",
    "natalTags": "친근함, 사교적, 안정",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 2,
    "natalSocial": 5,
    "natalAdventure": 1,
    "natalTone": "친근함·활기"
  },
  {
    "id": "BEER_006",
    "nameKo": "산미구엘 페일 필젠",
    "nameEn": "San Miguel Pale Pilsen",
    "brewery": "San Miguel Brewery",
    "country": "필리핀",
    "styleMajor": "청량 라거",
    "styleMinor": "Pale Lager",
    "abv": 5,
    "ibu": 18,
    "bitterness": 2,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 1,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "grain, light malt",
    "flavorSummary": "담백함, 산뜻함",
    "foodTags": "구이, 튀김, 스낵",
    "occasionTags": "캐주얼 모임",
    "natalTags": "활기, 친근함, 가벼움",
    "availability": "A",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 2,
    "natalSensory": 1,
    "natalSocial": 5,
    "natalAdventure": 1,
    "natalTone": "캐주얼·활기"
  },
  {
    "id": "BEER_007",
    "nameKo": "필스너 우르켈",
    "nameEn": "Pilsner Urquell",
    "brewery": "Plzeňský Prazdroj",
    "country": "체코",
    "styleMajor": "필스너",
    "styleMinor": "Czech Premium Pale Lager",
    "abv": 4.4,
    "ibu": 40,
    "bitterness": 4,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 3,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "saaz hop, bread, herbal",
    "flavorSummary": "쌉쌀함, 빵, 허브",
    "foodTags": "소시지, 치킨, 치즈",
    "occasionTags": "식사 반주, 모임",
    "natalTags": "정통, 자신감, 균형",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 2,
    "natalTone": "정통·자신감"
  },
  {
    "id": "BEER_008",
    "nameKo": "코젤 라거",
    "nameEn": "Kozel Premium Lager",
    "brewery": "Velkopopovický Kozel",
    "country": "체코",
    "styleMajor": "필스너",
    "styleMinor": "Czech Pale Lager",
    "abv": 4.6,
    "ibu": 25,
    "bitterness": 2,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 2,
    "body": 2,
    "carbonation": 3,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "malt, herbal",
    "flavorSummary": "부드러운 몰트, 낮은 쓴맛",
    "foodTags": "소시지, 닭구이",
    "occasionTags": "편안한 모임",
    "natalTags": "온화함, 친근함, 안정",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 2,
    "natalSocial": 5,
    "natalAdventure": 1,
    "natalTone": "온화함·안정"
  },
  {
    "id": "BEER_009",
    "nameKo": "비트부르거 프리미엄 필스",
    "nameEn": "Bitburger Premium Pils",
    "brewery": "Bitburger",
    "country": "독일",
    "styleMajor": "필스너",
    "styleMinor": "German Pils",
    "abv": 4.8,
    "ibu": 33,
    "bitterness": 4,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 3,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "herbal hop, grain",
    "flavorSummary": "드라이, 쌉쌀, 선명함",
    "foodTags": "소시지, 튀김",
    "occasionTags": "식사 반주",
    "natalTags": "정돈, 이성적, 선명함",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 2,
    "natalSocial": 3,
    "natalAdventure": 2,
    "natalTone": "이성적·정돈"
  },
  {
    "id": "BEER_010",
    "nameKo": "크롬바허 필스",
    "nameEn": "Krombacher Pils",
    "brewery": "Krombacher",
    "country": "독일",
    "styleMajor": "필스너",
    "styleMinor": "German Pils",
    "abv": 4.8,
    "ibu": 24,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 2,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 1,
    "aromaTags": "floral, herbal, grain",
    "flavorSummary": "깔끔, 드라이",
    "foodTags": "치킨, 피자",
    "occasionTags": "모임",
    "natalTags": "절제, 균형, 담백함",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 2,
    "natalSocial": 4,
    "natalAdventure": 1,
    "natalTone": "균형·담백함"
  },
  {
    "id": "BEER_011",
    "nameKo": "바르슈타이너 프리미엄 베룸",
    "nameEn": "Warsteiner Premium Verum",
    "brewery": "Warsteiner",
    "country": "독일",
    "styleMajor": "필스너",
    "styleMinor": "German Pils",
    "abv": 4.8,
    "ibu": 30,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 2,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 1,
    "aromaTags": "herbal, grain",
    "flavorSummary": "드라이, 은은한 홉",
    "foodTags": "해산물, 샌드위치",
    "occasionTags": "가벼운 식사",
    "natalTags": "정갈함, 안정, 실용적",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 2,
    "natalSocial": 3,
    "natalAdventure": 1,
    "natalTone": "정갈함·절제"
  },
  {
    "id": "BEER_012",
    "nameKo": "그롤쉬 프리미엄 필스너",
    "nameEn": "Grolsch Premium Pilsner",
    "brewery": "Grolsch",
    "country": "네덜란드",
    "styleMajor": "필스너",
    "styleMinor": "European Pilsner",
    "abv": 5,
    "ibu": 28,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 3,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "herbal, grassy",
    "flavorSummary": "홉향, 드라이",
    "foodTags": "치즈, 튀김",
    "occasionTags": "모임",
    "natalTags": "개성, 명료함, 독립적",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 2,
    "natalTone": "독립적·명료함"
  },
  {
    "id": "BEER_013",
    "nameKo": "바이엔슈테판 오리지널 헬레스",
    "nameEn": "Weihenstephaner Original Helles",
    "brewery": "Weihenstephan",
    "country": "독일",
    "styleMajor": "헬레스·몰티 라거",
    "styleMinor": "Munich Helles",
    "abv": 5.1,
    "ibu": 21,
    "bitterness": 2,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 2,
    "body": 3,
    "carbonation": 3,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "bread, malt, floral",
    "flavorSummary": "고소한 몰트, 부드러움",
    "foodTags": "소시지, 닭구이, 샐러드",
    "occasionTags": "편안한 저녁",
    "natalTags": "안정, 따뜻함, 전통",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 1,
    "natalSensory": 3,
    "natalSocial": 3,
    "natalAdventure": 1,
    "natalTone": "따뜻함·안정"
  },
  {
    "id": "BEER_014",
    "nameKo": "파울라너 뮌히너 헬",
    "nameEn": "Paulaner Münchner Hell",
    "brewery": "Paulaner",
    "country": "독일",
    "styleMajor": "헬레스·몰티 라거",
    "styleMinor": "Munich Helles",
    "abv": 4.9,
    "ibu": 20,
    "bitterness": 2,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 2,
    "body": 3,
    "carbonation": 3,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "malt, bread, faint floral",
    "flavorSummary": "고소함, 둥근 질감",
    "foodTags": "소시지, 치킨",
    "occasionTags": "식사 반주",
    "natalTags": "편안함, 친근함, 안정",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 1,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 1,
    "natalTone": "편안함·친근함"
  },
  {
    "id": "BEER_015",
    "nameKo": "호프브로이 오리지널",
    "nameEn": "Hofbräu Original",
    "brewery": "Hofbräu München",
    "country": "독일",
    "styleMajor": "헬레스·몰티 라거",
    "styleMinor": "Munich Helles",
    "abv": 5.1,
    "ibu": 24,
    "bitterness": 2,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 2,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 1,
    "aromaTags": "bread, grain, herbal",
    "flavorSummary": "고소, 깔끔",
    "foodTags": "소시지, 슈니첼",
    "occasionTags": "모임",
    "natalTags": "활기, 전통, 사교적",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 2,
    "natalSocial": 5,
    "natalAdventure": 1,
    "natalTone": "전통·활기"
  },
  {
    "id": "BEER_016",
    "nameKo": "아잉거 라거 헬",
    "nameEn": "Ayinger Lager Hell",
    "brewery": "Ayinger",
    "country": "독일",
    "styleMajor": "헬레스·몰티 라거",
    "styleMinor": "Munich Helles",
    "abv": 4.9,
    "ibu": 18,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 2,
    "body": 3,
    "carbonation": 3,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "bread, honeyed malt",
    "flavorSummary": "부드럽고 고소함",
    "foodTags": "구운 닭, 치즈",
    "occasionTags": "조용한 식사",
    "natalTags": "온화함, 섬세함, 안정",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 1,
    "natalSensory": 3,
    "natalSocial": 3,
    "natalAdventure": 1,
    "natalTone": "섬세함·온화함"
  },
  {
    "id": "BEER_017",
    "nameKo": "해커 프쇼르 뮌히너 골드",
    "nameEn": "Hacker-Pschorr Münchner Gold",
    "brewery": "Hacker-Pschorr",
    "country": "독일",
    "styleMajor": "헬레스·몰티 라거",
    "styleMinor": "Munich Helles",
    "abv": 5.5,
    "ibu": 22,
    "bitterness": 2,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 2,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 1,
    "aromaTags": "malt, bread, light herb",
    "flavorSummary": "몰티, 둥글고 깔끔",
    "foodTags": "소시지, 샌드위치",
    "occasionTags": "식사 반주",
    "natalTags": "풍성함, 전통, 여유",
    "availability": "C",
    "confidence": "낮음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 1,
    "natalTone": "풍성함·여유"
  },
  {
    "id": "BEER_018",
    "nameKo": "사무엘 아담스 보스턴 라거",
    "nameEn": "Samuel Adams Boston Lager",
    "brewery": "Boston Beer Co.",
    "country": "미국",
    "styleMajor": "헬레스·몰티 라거",
    "styleMinor": "Vienna/Amber Lager",
    "abv": 5,
    "ibu": 30,
    "bitterness": 3,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 3,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "caramel, floral hop, toast",
    "flavorSummary": "카라멜, 토스트, 홉 균형",
    "foodTags": "버거, 바비큐",
    "occasionTags": "저녁 모임",
    "natalTags": "균형, 도시적, 친근함",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 2,
    "natalTone": "도시적·균형"
  },
  {
    "id": "BEER_019",
    "nameKo": "바이엔슈테판 헤페바이스",
    "nameEn": "Weihenstephaner Hefeweissbier",
    "brewery": "Weihenstephan",
    "country": "독일",
    "styleMajor": "바이젠",
    "styleMinor": "Hefeweizen",
    "abv": 5.4,
    "ibu": 14,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 5,
    "body": 3,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 2,
    "aromaTags": "banana, clove, wheat",
    "flavorSummary": "바나나, 정향, 부드러움",
    "foodTags": "소시지, 샐러드, 해산물",
    "occasionTags": "브런치, 편안한 모임",
    "natalTags": "따뜻함, 유쾌함, 감성적",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 4,
    "natalSocial": 4,
    "natalAdventure": 2,
    "natalTone": "따뜻함·유쾌함"
  },
  {
    "id": "BEER_020",
    "nameKo": "파울라너 바이스비어",
    "nameEn": "Paulaner Weissbier",
    "brewery": "Paulaner",
    "country": "독일",
    "styleMajor": "바이젠",
    "styleMinor": "Hefeweizen",
    "abv": 5.5,
    "ibu": 13,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 2,
    "aromaTags": "banana, clove, yeast",
    "flavorSummary": "부드러운 밀, 과일",
    "foodTags": "소시지, 치킨",
    "occasionTags": "모임",
    "natalTags": "친근함, 풍성함, 낙천적",
    "availability": "A",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 4,
    "natalSocial": 5,
    "natalAdventure": 2,
    "natalTone": "낙천적·친근함"
  },
  {
    "id": "BEER_021",
    "nameKo": "에딩거 바이스비어",
    "nameEn": "Erdinger Weissbier",
    "brewery": "Erdinger",
    "country": "독일",
    "styleMajor": "바이젠",
    "styleMinor": "Hefeweizen",
    "abv": 5.3,
    "ibu": 13,
    "bitterness": 1,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "banana, yeast, wheat",
    "flavorSummary": "부드러움, 깔끔",
    "foodTags": "샐러드, 소시지",
    "occasionTags": "가벼운 모임",
    "natalTags": "온화함, 균형, 편안함",
    "availability": "A",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 1,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 1,
    "natalTone": "온화함·편안함"
  },
  {
    "id": "BEER_022",
    "nameKo": "프란치스카너 헤페바이스",
    "nameEn": "Franziskaner Hefe-Weissbier",
    "brewery": "Spaten-Franziskaner",
    "country": "독일",
    "styleMajor": "바이젠",
    "styleMinor": "Hefeweizen",
    "abv": 5,
    "ibu": 12,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "banana, clove, bread",
    "flavorSummary": "과일, 밀, 효모",
    "foodTags": "치킨, 소시지",
    "occasionTags": "편안한 저녁",
    "natalTags": "부드러움, 친근함, 전통",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 4,
    "natalSocial": 4,
    "natalAdventure": 2,
    "natalTone": "전통·부드러움"
  },
  {
    "id": "BEER_023",
    "nameKo": "슈나이더 바이세 TAP7",
    "nameEn": "Schneider Weisse TAP7 Original",
    "brewery": "Schneider Weisse",
    "country": "독일",
    "styleMajor": "바이젠",
    "styleMinor": "Hefeweizen",
    "abv": 5.4,
    "ibu": 14,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "banana, clove, nutmeg, malt",
    "flavorSummary": "진한 밀, 향신료, 과일",
    "foodTags": "돼지고기, 소시지",
    "occasionTags": "천천히 마시는 저녁",
    "natalTags": "복합적, 감성적, 전통",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 5,
    "natalSocial": 3,
    "natalAdventure": 3,
    "natalTone": "감성적·복합적"
  },
  {
    "id": "BEER_024",
    "nameKo": "카이저돔 헤페바이스",
    "nameEn": "Kaiserdom Hefe-Weissbier",
    "brewery": "Kaiserdom",
    "country": "독일",
    "styleMajor": "바이젠",
    "styleMinor": "Hefeweizen",
    "abv": 4.7,
    "ibu": 12,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 1,
    "aromaTags": "banana, wheat, yeast",
    "flavorSummary": "부드러움, 달큰한 곡물",
    "foodTags": "소시지, 튀김",
    "occasionTags": "캐주얼 모임",
    "natalTags": "가벼운 낙천성, 편안함",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 1,
    "natalTone": "낙천적·편안함"
  },
  {
    "id": "BEER_025",
    "nameKo": "호가든 화이트",
    "nameEn": "Hoegaarden White",
    "brewery": "Hoegaarden",
    "country": "벨기에",
    "styleMajor": "위트비어",
    "styleMinor": "Belgian Witbier",
    "abv": 4.9,
    "ibu": 15,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 2,
    "aroma": 5,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "orange peel, coriander, wheat",
    "flavorSummary": "시트러스, 향신료, 부드러움",
    "foodTags": "샐러드, 해산물, 치킨",
    "occasionTags": "브런치, 가벼운 모임",
    "natalTags": "밝음, 친화적, 산뜻함",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 2,
    "natalSensory": 4,
    "natalSocial": 5,
    "natalAdventure": 2,
    "natalTone": "밝음·친화적"
  },
  {
    "id": "BEER_026",
    "nameKo": "크로넨버그 1664 블랑",
    "nameEn": "Kronenbourg 1664 Blanc",
    "brewery": "Kronenbourg",
    "country": "프랑스",
    "styleMajor": "위트비어",
    "styleMinor": "Wheat/Wit-style Beer",
    "abv": 5,
    "ibu": 12,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 2,
    "aroma": 5,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "citrus, tropical fruit, spice",
    "flavorSummary": "달큰한 시트러스, 부드러움",
    "foodTags": "치킨, 샐러드, 과일",
    "occasionTags": "파티, 데이트",
    "natalTags": "화사함, 세련됨, 사교적",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 3,
    "natalStimulation": 2,
    "natalSensory": 5,
    "natalSocial": 5,
    "natalAdventure": 2,
    "natalTone": "화사함·세련됨"
  },
  {
    "id": "BEER_027",
    "nameKo": "블루문 벨지안 화이트",
    "nameEn": "Blue Moon Belgian White",
    "brewery": "Blue Moon Brewing",
    "country": "미국",
    "styleMajor": "위트비어",
    "styleMinor": "Belgian-style Witbier",
    "abv": 5.4,
    "ibu": 9,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 2,
    "aroma": 4,
    "body": 3,
    "carbonation": 3,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "orange, coriander, wheat",
    "flavorSummary": "오렌지, 밀, 은은한 향신료",
    "foodTags": "치킨, 타코, 샐러드",
    "occasionTags": "모임",
    "natalTags": "유쾌함, 부드러움, 친근함",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 2,
    "natalSensory": 4,
    "natalSocial": 5,
    "natalAdventure": 2,
    "natalTone": "유쾌함·부드러움"
  },
  {
    "id": "BEER_028",
    "nameKo": "히타치노 네스트 화이트 에일",
    "nameEn": "Hitachino Nest White Ale",
    "brewery": "Kiuchi Brewery",
    "country": "일본",
    "styleMajor": "위트비어",
    "styleMinor": "Belgian-style Witbier",
    "abv": 5.5,
    "ibu": 13,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 2,
    "aroma": 5,
    "body": 3,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "coriander, orange, nutmeg",
    "flavorSummary": "복합적 향신료, 시트러스",
    "foodTags": "회, 해산물, 샐러드",
    "occasionTags": "데이트, 특별한 식사",
    "natalTags": "섬세함, 호기심, 개성",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 5,
    "natalSocial": 3,
    "natalAdventure": 4,
    "natalTone": "호기심·섬세함"
  },
  {
    "id": "BEER_029",
    "nameKo": "블랑쉬 드 나뮈르",
    "nameEn": "Blanche de Namur",
    "brewery": "Brasserie du Bocq",
    "country": "벨기에",
    "styleMajor": "위트비어",
    "styleMinor": "Belgian Witbier",
    "abv": 4.5,
    "ibu": 11,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 2,
    "aroma": 4,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "coriander, citrus, wheat",
    "flavorSummary": "가볍고 향긋함",
    "foodTags": "해산물, 샐러드",
    "occasionTags": "브런치",
    "natalTags": "우아함, 가벼움, 섬세함",
    "availability": "C",
    "confidence": "낮음",
    "natalStability": 4,
    "natalStimulation": 2,
    "natalSensory": 4,
    "natalSocial": 4,
    "natalAdventure": 3,
    "natalTone": "우아함·가벼움"
  },
  {
    "id": "BEER_030",
    "nameKo": "세인트 버나두스 위트",
    "nameEn": "St. Bernardus Wit",
    "brewery": "St. Bernardus",
    "country": "벨기에",
    "styleMajor": "위트비어",
    "styleMinor": "Belgian Witbier",
    "abv": 5.5,
    "ibu": 15,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 2,
    "aroma": 5,
    "body": 3,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "citrus, coriander, spice",
    "flavorSummary": "향신료, 밀, 시트러스",
    "foodTags": "해산물, 치즈",
    "occasionTags": "여유로운 식사",
    "natalTags": "복합적, 따뜻함, 개성",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 5,
    "natalSocial": 3,
    "natalAdventure": 4,
    "natalTone": "복합적·따뜻함"
  },
  {
    "id": "BEER_031",
    "nameKo": "시에라 네바다 페일 에일",
    "nameEn": "Sierra Nevada Pale Ale",
    "brewery": "Sierra Nevada",
    "country": "미국",
    "styleMajor": "페일 에일",
    "styleMinor": "American Pale Ale",
    "abv": 5.6,
    "ibu": 38,
    "bitterness": 3,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "pine, citrus, caramel malt",
    "flavorSummary": "홉과 몰트 균형, 쌉쌀함",
    "foodTags": "버거, 치킨, 피자",
    "occasionTags": "모임",
    "natalTags": "선명함, 자신감, 활동적",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 4,
    "natalAdventure": 3,
    "natalTone": "자신감·활동적"
  },
  {
    "id": "BEER_032",
    "nameKo": "쿠퍼스 오리지널 페일 에일",
    "nameEn": "Coopers Original Pale Ale",
    "brewery": "Coopers",
    "country": "호주",
    "styleMajor": "페일 에일",
    "styleMinor": "Australian Pale Ale",
    "abv": 4.5,
    "ibu": 25,
    "bitterness": 2,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 3,
    "body": 3,
    "carbonation": 3,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "fruit ester, malt, floral",
    "flavorSummary": "과일, 몰트, 부드러움",
    "foodTags": "피자, 치킨",
    "occasionTags": "캐주얼 모임",
    "natalTags": "친근함, 균형, 편안함",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 2,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 2,
    "natalTone": "친근함·균형"
  },
  {
    "id": "BEER_033",
    "nameKo": "코나 빅 웨이브",
    "nameEn": "Kona Big Wave",
    "brewery": "Kona Brewing",
    "country": "미국",
    "styleMajor": "페일 에일",
    "styleMinor": "Golden Ale",
    "abv": 4.4,
    "ibu": 21,
    "bitterness": 2,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 4,
    "body": 2,
    "carbonation": 3,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "tropical fruit, floral",
    "flavorSummary": "가벼운 열대과일, 산뜻함",
    "foodTags": "타코, 해산물",
    "occasionTags": "야외, 파티",
    "natalTags": "햇살, 자유, 낙천성",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 3,
    "natalStimulation": 2,
    "natalSensory": 4,
    "natalSocial": 5,
    "natalAdventure": 3,
    "natalTone": "자유·낙천성"
  },
  {
    "id": "BEER_034",
    "nameKo": "맥파이 페일 에일",
    "nameEn": "Magpie Pale Ale",
    "brewery": "Magpie Brewing",
    "country": "대한민국",
    "styleMajor": "페일 에일",
    "styleMinor": "American Pale Ale",
    "abv": 4.8,
    "ibu": 35,
    "bitterness": 3,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "citrus, pine, malt",
    "flavorSummary": "시트러스, 균형 잡힌 홉",
    "foodTags": "버거, 피자",
    "occasionTags": "친구 모임",
    "natalTags": "도시적, 활동적, 친근함",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 4,
    "natalAdventure": 3,
    "natalTone": "도시적·활동적"
  },
  {
    "id": "BEER_035",
    "nameKo": "크래프트브로스 원더 페일 에일",
    "nameEn": "Craftbros Wonder Pale Ale",
    "brewery": "Craftbros",
    "country": "대한민국",
    "styleMajor": "페일 에일",
    "styleMinor": "American Pale Ale",
    "abv": 5,
    "ibu": 35,
    "bitterness": 3,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "citrus, floral, tropical",
    "flavorSummary": "과일홉, 산뜻함",
    "foodTags": "치킨, 버거",
    "occasionTags": "친구 모임",
    "natalTags": "창의적, 밝음, 활동적",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 4,
    "natalAdventure": 4,
    "natalTone": "창의적·밝음"
  },
  {
    "id": "BEER_036",
    "nameKo": "사무엘 스미스 페일 에일",
    "nameEn": "Samuel Smith Pale Ale",
    "brewery": "Samuel Smith",
    "country": "영국",
    "styleMajor": "페일 에일",
    "styleMinor": "English Pale Ale",
    "abv": 5,
    "ibu": 30,
    "bitterness": 3,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 3,
    "body": 3,
    "carbonation": 2,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "earthy hop, caramel, fruit",
    "flavorSummary": "몰트 중심, 영국식 홉",
    "foodTags": "치즈, 로스트비프",
    "occasionTags": "조용한 저녁",
    "natalTags": "고전적, 차분함, 균형",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 2,
    "natalSensory": 4,
    "natalSocial": 3,
    "natalAdventure": 2,
    "natalTone": "고전적·차분함"
  },
  {
    "id": "BEER_037",
    "nameKo": "파운더스 올 데이 IPA",
    "nameEn": "Founders All Day IPA",
    "brewery": "Founders",
    "country": "미국",
    "styleMajor": "세션·라이트 IPA",
    "styleMinor": "Session IPA",
    "abv": 4.7,
    "ibu": 42,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 4,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "citrus, floral, tropical",
    "flavorSummary": "홉향 강함, 가벼운 바디",
    "foodTags": "버거, 치킨, 나초",
    "occasionTags": "긴 모임, 야외",
    "natalTags": "활동적, 자유, 사교적",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 5,
    "natalAdventure": 3,
    "natalTone": "자유·활동적"
  },
  {
    "id": "BEER_038",
    "nameKo": "브루독 데드 포니 클럽",
    "nameEn": "BrewDog Dead Pony Club",
    "brewery": "BrewDog",
    "country": "영국",
    "styleMajor": "세션·라이트 IPA",
    "styleMinor": "Session Pale Ale",
    "abv": 3.8,
    "ibu": 35,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 4,
    "body": 2,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "citrus, tropical, pine",
    "flavorSummary": "홉 중심, 가벼움",
    "foodTags": "타코, 치킨",
    "occasionTags": "가벼운 모임",
    "natalTags": "장난기, 활동적, 가벼움",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 2,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 5,
    "natalAdventure": 4,
    "natalTone": "장난기·활동적"
  },
  {
    "id": "BEER_039",
    "nameKo": "미켈러 버스트 IPA",
    "nameEn": "Mikkeller Burst IPA",
    "brewery": "Mikkeller",
    "country": "덴마크",
    "styleMajor": "세션·라이트 IPA",
    "styleMinor": "Session IPA",
    "abv": 4.5,
    "ibu": 40,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 5,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "tropical, citrus, resin",
    "flavorSummary": "향긋한 홉, 드라이",
    "foodTags": "버거, 피자",
    "occasionTags": "파티",
    "natalTags": "실험적, 유쾌함, 현대적",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 2,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 4,
    "natalAdventure": 5,
    "natalTone": "실험적·현대적"
  },
  {
    "id": "BEER_040",
    "nameKo": "구스 아일랜드 미드웨이 IPA",
    "nameEn": "Goose Island Midway IPA",
    "brewery": "Goose Island",
    "country": "미국",
    "styleMajor": "세션·라이트 IPA",
    "styleMinor": "Session IPA",
    "abv": 4.1,
    "ibu": 30,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 4,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "citrus, tropical",
    "flavorSummary": "가벼운 홉, 산뜻함",
    "foodTags": "치킨, 버거",
    "occasionTags": "모임",
    "natalTags": "사교적, 가벼운 모험",
    "availability": "C",
    "confidence": "낮음",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 5,
    "natalAdventure": 3,
    "natalTone": "사교적·모험"
  },
  {
    "id": "BEER_041",
    "nameKo": "로우 로우 IPA",
    "nameEn": "Low Low IPA",
    "brewery": "국내 유통 브랜드",
    "country": "대한민국/수입",
    "styleMajor": "세션·라이트 IPA",
    "styleMinor": "Light IPA",
    "abv": 4,
    "ibu": 35,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 4,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "citrus, hop",
    "flavorSummary": "가벼운 IPA, 드라이",
    "foodTags": "치킨, 스낵",
    "occasionTags": "가벼운 술자리",
    "natalTags": "활동적, 부담없음, 캐주얼",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 3,
    "natalTone": "캐주얼·활동적"
  },
  {
    "id": "BEER_042",
    "nameKo": "홉스플래쉬 IPA",
    "nameEn": "Hopsplash IPA",
    "brewery": "국내 유통 브랜드",
    "country": "대한민국/수입",
    "styleMajor": "세션·라이트 IPA",
    "styleMinor": "Light/Session IPA",
    "abv": 4.5,
    "ibu": 40,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 4,
    "body": 2,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "citrus, tropical hop",
    "flavorSummary": "홉향, 산뜻함",
    "foodTags": "버거, 치킨",
    "occasionTags": "친구 모임",
    "natalTags": "쾌활함, 모험심, 캐주얼",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 2,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 4,
    "natalAdventure": 4,
    "natalTone": "쾌활함·모험"
  },
  {
    "id": "BEER_043",
    "nameKo": "구스 아일랜드 IPA",
    "nameEn": "Goose Island IPA",
    "brewery": "Goose Island",
    "country": "미국",
    "styleMajor": "IPA",
    "styleMinor": "American IPA",
    "abv": 5.9,
    "ibu": 55,
    "bitterness": 4,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 5,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "grapefruit, pine, citrus",
    "flavorSummary": "쌉쌀, 자몽, 홉",
    "foodTags": "버거, 매운 음식",
    "occasionTags": "친구 모임",
    "natalTags": "대담함, 활기, 직선적",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 2,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 4,
    "natalAdventure": 4,
    "natalTone": "대담함·활기"
  },
  {
    "id": "BEER_044",
    "nameKo": "브루독 펑크 IPA",
    "nameEn": "BrewDog Punk IPA",
    "brewery": "BrewDog",
    "country": "영국",
    "styleMajor": "IPA",
    "styleMinor": "American-style IPA",
    "abv": 5.4,
    "ibu": 35,
    "bitterness": 4,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 5,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "tropical, grapefruit, pine",
    "flavorSummary": "열대과일, 홉, 쌉쌀함",
    "foodTags": "버거, 타코",
    "occasionTags": "파티",
    "natalTags": "반항적, 창의적, 대담함",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 1,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 4,
    "natalAdventure": 5,
    "natalTone": "반항적·창의적"
  },
  {
    "id": "BEER_045",
    "nameKo": "라구니타스 IPA",
    "nameEn": "Lagunitas IPA",
    "brewery": "Lagunitas",
    "country": "미국",
    "styleMajor": "IPA",
    "styleMinor": "American IPA",
    "abv": 6.2,
    "ibu": 51,
    "bitterness": 4,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 3,
    "beginner": 3,
    "adventure": 4,
    "aromaTags": "pine, citrus, caramel",
    "flavorSummary": "강한 홉, 몰트 받침",
    "foodTags": "바비큐, 버거",
    "occasionTags": "저녁 모임",
    "natalTags": "강렬함, 자신감, 자유",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 2,
    "natalStimulation": 5,
    "natalSensory": 5,
    "natalSocial": 3,
    "natalAdventure": 4,
    "natalTone": "자유·강렬함"
  },
  {
    "id": "BEER_046",
    "nameKo": "에일스미스 IPA",
    "nameEn": "AleSmith IPA",
    "brewery": "AleSmith",
    "country": "미국",
    "styleMajor": "IPA",
    "styleMinor": "American IPA",
    "abv": 7.25,
    "ibu": 73,
    "bitterness": 5,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 3,
    "beginner": 3,
    "adventure": 5,
    "aromaTags": "citrus, pine, tropical",
    "flavorSummary": "강한 쓴맛, 진한 홉",
    "foodTags": "매운 음식, 바비큐",
    "occasionTags": "집중해서 마시는 자리",
    "natalTags": "강렬함, 도전, 집중",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 1,
    "natalStimulation": 5,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 5,
    "natalTone": "도전·집중"
  },
  {
    "id": "BEER_047",
    "nameKo": "레이서 5 IPA",
    "nameEn": "Racer 5 IPA",
    "brewery": "Bear Republic",
    "country": "미국",
    "styleMajor": "IPA",
    "styleMinor": "American IPA",
    "abv": 7.5,
    "ibu": 75,
    "bitterness": 5,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 3,
    "beginner": 3,
    "adventure": 5,
    "aromaTags": "pine, citrus, resin",
    "flavorSummary": "강한 홉, 몰트, 쌉쌀함",
    "foodTags": "버거, 바비큐",
    "occasionTags": "취향 확실한 모임",
    "natalTags": "모험, 에너지, 독립적",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 1,
    "natalStimulation": 5,
    "natalSensory": 5,
    "natalSocial": 3,
    "natalAdventure": 5,
    "natalTone": "에너지·독립적"
  },
  {
    "id": "BEER_048",
    "nameKo": "맥파이 IPA",
    "nameEn": "Magpie IPA",
    "brewery": "Magpie Brewing",
    "country": "대한민국",
    "styleMajor": "IPA",
    "styleMinor": "American IPA",
    "abv": 6.5,
    "ibu": 60,
    "bitterness": 4,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 5,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 4,
    "aromaTags": "citrus, pine, tropical",
    "flavorSummary": "홉 중심, 선명한 쓴맛",
    "foodTags": "버거, 매운 음식",
    "occasionTags": "친구 모임",
    "natalTags": "도시적, 대담함, 활동적",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 2,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 4,
    "natalAdventure": 4,
    "natalTone": "도시적·대담함"
  },
  {
    "id": "BEER_049",
    "nameKo": "듀벨",
    "nameEn": "Duvel",
    "brewery": "Duvel Moortgat",
    "country": "벨기에",
    "styleMajor": "벨기에 에일",
    "styleMinor": "Belgian Strong Golden Ale",
    "abv": 8.5,
    "ibu": 32,
    "bitterness": 3,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 5,
    "body": 3,
    "carbonation": 5,
    "beginner": 3,
    "adventure": 5,
    "aromaTags": "pear, citrus, spice, floral",
    "flavorSummary": "드라이, 과일, 향신료",
    "foodTags": "치즈, 해산물",
    "occasionTags": "특별한 저녁",
    "natalTags": "화려함, 독립적, 강렬함",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 2,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 4,
    "natalAdventure": 5,
    "natalTone": "화려함·독립적"
  },
  {
    "id": "BEER_050",
    "nameKo": "시메이 블루",
    "nameEn": "Chimay Blue",
    "brewery": "Chimay",
    "country": "벨기에",
    "styleMajor": "벨기에 에일",
    "styleMinor": "Belgian Dark Strong Ale",
    "abv": 9,
    "ibu": 35,
    "bitterness": 2,
    "sweetness": 4,
    "acidity": 1,
    "aroma": 5,
    "body": 5,
    "carbonation": 3,
    "beginner": 2,
    "adventure": 5,
    "aromaTags": "dark fruit, caramel, spice",
    "flavorSummary": "건과일, 카라멜, 깊이",
    "foodTags": "스테이크, 숙성치즈",
    "occasionTags": "조용한 밤",
    "natalTags": "깊이, 성찰, 전통",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 4,
    "natalTone": "깊이·성찰"
  },
  {
    "id": "BEER_051",
    "nameKo": "시메이 트리플",
    "nameEn": "Chimay Triple",
    "brewery": "Chimay",
    "country": "벨기에",
    "styleMajor": "벨기에 에일",
    "styleMinor": "Belgian Tripel",
    "abv": 8,
    "ibu": 35,
    "bitterness": 3,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 4,
    "beginner": 3,
    "adventure": 4,
    "aromaTags": "fruit, floral, spice",
    "flavorSummary": "과일, 향신료, 드라이",
    "foodTags": "치즈, 닭요리",
    "occasionTags": "특별한 식사",
    "natalTags": "세련됨, 밝음, 복합적",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 3,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 3,
    "natalAdventure": 4,
    "natalTone": "세련됨·복합적"
  },
  {
    "id": "BEER_052",
    "nameKo": "트라피스트 로슈포르 8",
    "nameEn": "Trappistes Rochefort 8",
    "brewery": "Rochefort",
    "country": "벨기에",
    "styleMajor": "벨기에 에일",
    "styleMinor": "Belgian Dark Strong Ale",
    "abv": 9.2,
    "ibu": 22,
    "bitterness": 2,
    "sweetness": 4,
    "acidity": 1,
    "aroma": 5,
    "body": 5,
    "carbonation": 3,
    "beginner": 2,
    "adventure": 5,
    "aromaTags": "fig, plum, caramel, spice",
    "flavorSummary": "건과일, 몰트, 깊이",
    "foodTags": "스튜, 치즈",
    "occasionTags": "혼술, 느린 밤",
    "natalTags": "성찰, 신비, 깊이",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 5,
    "natalSensory": 5,
    "natalSocial": 1,
    "natalAdventure": 5,
    "natalTone": "신비·성찰"
  },
  {
    "id": "BEER_053",
    "nameKo": "세인트 버나두스 앱 12",
    "nameEn": "St. Bernardus Abt 12",
    "brewery": "St. Bernardus",
    "country": "벨기에",
    "styleMajor": "벨기에 에일",
    "styleMinor": "Belgian Quadrupel",
    "abv": 10,
    "ibu": 20,
    "bitterness": 2,
    "sweetness": 5,
    "acidity": 1,
    "aroma": 5,
    "body": 5,
    "carbonation": 3,
    "beginner": 2,
    "adventure": 5,
    "aromaTags": "dark fruit, caramel, spice",
    "flavorSummary": "달큰한 건과일, 깊은 몰트",
    "foodTags": "스테이크, 치즈, 디저트",
    "occasionTags": "조용한 밤",
    "natalTags": "풍요, 깊이, 낭만적",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 5,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 5,
    "natalTone": "풍요·낭만"
  },
  {
    "id": "BEER_054",
    "nameKo": "오르발",
    "nameEn": "Orval",
    "brewery": "Brasserie d'Orval",
    "country": "벨기에",
    "styleMajor": "벨기에 에일",
    "styleMinor": "Belgian Pale/Trappist Ale",
    "abv": 6.2,
    "ibu": 36,
    "bitterness": 4,
    "sweetness": 1,
    "acidity": 2,
    "aroma": 5,
    "body": 3,
    "carbonation": 4,
    "beginner": 2,
    "adventure": 5,
    "aromaTags": "herbal, citrus, brett, floral",
    "flavorSummary": "드라이, 허브, 독특한 효모",
    "foodTags": "치즈, 해산물",
    "occasionTags": "혼술, 특별한 식사",
    "natalTags": "독창성, 지적 호기심, 독립",
    "availability": "C",
    "confidence": "중간",
    "natalStability": 2,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 5,
    "natalTone": "지적·독창적"
  },
  {
    "id": "BEER_055",
    "nameKo": "코젤 다크",
    "nameEn": "Kozel Dark",
    "brewery": "Velkopopovický Kozel",
    "country": "체코",
    "styleMajor": "앰버·다크 라거",
    "styleMinor": "Czech Dark Lager",
    "abv": 3.8,
    "ibu": 18,
    "bitterness": 1,
    "sweetness": 4,
    "acidity": 1,
    "aroma": 3,
    "body": 3,
    "carbonation": 3,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "caramel, toast, cocoa",
    "flavorSummary": "달큰한 카라멜, 부드러움",
    "foodTags": "바비큐, 소시지",
    "occasionTags": "편안한 저녁",
    "natalTags": "따뜻함, 친근함, 안정",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 1,
    "natalTone": "따뜻함·편안함"
  },
  {
    "id": "BEER_056",
    "nameKo": "네그라 모델로",
    "nameEn": "Negra Modelo",
    "brewery": "Grupo Modelo",
    "country": "멕시코",
    "styleMajor": "앰버·다크 라거",
    "styleMinor": "Munich Dunkel-style Lager",
    "abv": 5.4,
    "ibu": 20,
    "bitterness": 2,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 3,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "caramel, nut, toast",
    "flavorSummary": "몰티, 견과, 카라멜",
    "foodTags": "타코, 바비큐",
    "occasionTags": "저녁 모임",
    "natalTags": "성숙함, 편안함, 균형",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 2,
    "natalTone": "성숙함·균형"
  },
  {
    "id": "BEER_057",
    "nameKo": "아잉거 알트바이리쉬 둔켈",
    "nameEn": "Ayinger Altbairisch Dunkel",
    "brewery": "Ayinger",
    "country": "독일",
    "styleMajor": "앰버·다크 라거",
    "styleMinor": "Munich Dunkel",
    "abv": 5,
    "ibu": 21,
    "bitterness": 2,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 4,
    "body": 4,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "toast, chocolate, bread",
    "flavorSummary": "구운 빵, 초콜릿, 몰트",
    "foodTags": "소시지, 로스트",
    "occasionTags": "조용한 저녁",
    "natalTags": "전통, 안정, 깊이",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 2,
    "natalAdventure": 2,
    "natalTone": "전통·깊이"
  },
  {
    "id": "BEER_058",
    "nameKo": "쾨스트리처 슈바르츠비어",
    "nameEn": "Köstritzer Schwarzbier",
    "brewery": "Köstritzer",
    "country": "독일",
    "styleMajor": "앰버·다크 라거",
    "styleMinor": "Schwarzbier",
    "abv": 4.8,
    "ibu": 25,
    "bitterness": 2,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "coffee, toast, chocolate",
    "flavorSummary": "로스팅, 드라이, 가벼운 커피",
    "foodTags": "소시지, 바비큐",
    "occasionTags": "식사 반주",
    "natalTags": "차분함, 지적, 균형",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 3,
    "natalAdventure": 3,
    "natalTone": "차분함·지적"
  },
  {
    "id": "BEER_059",
    "nameKo": "호프브로이 둔켈",
    "nameEn": "Hofbräu Dunkel",
    "brewery": "Hofbräu München",
    "country": "독일",
    "styleMajor": "앰버·다크 라거",
    "styleMinor": "Munich Dunkel",
    "abv": 5.5,
    "ibu": 23,
    "bitterness": 2,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 3,
    "body": 4,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "bread crust, caramel, malt",
    "flavorSummary": "고소한 몰트, 카라멜",
    "foodTags": "돼지고기, 소시지",
    "occasionTags": "저녁 식사",
    "natalTags": "따뜻함, 전통, 안정",
    "availability": "C",
    "confidence": "낮음",
    "natalStability": 5,
    "natalStimulation": 2,
    "natalSensory": 3,
    "natalSocial": 4,
    "natalAdventure": 2,
    "natalTone": "따뜻함·전통"
  },
  {
    "id": "BEER_060",
    "nameKo": "바이엔슈테판 헤페바이스 둔켈",
    "nameEn": "Weihenstephaner Hefeweissbier Dunkel",
    "brewery": "Weihenstephan",
    "country": "독일",
    "styleMajor": "앰버·다크 라거",
    "styleMinor": "Dunkelweizen",
    "abv": 5.3,
    "ibu": 14,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 4,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "banana, clove, caramel, bread",
    "flavorSummary": "과일효모, 구운 몰트",
    "foodTags": "소시지, 로스트",
    "occasionTags": "편안한 밤",
    "natalTags": "따뜻함, 감성적, 깊이",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 5,
    "natalSocial": 3,
    "natalAdventure": 3,
    "natalTone": "감성적·따뜻함"
  },
  {
    "id": "BEER_061",
    "nameKo": "기네스 드래프트",
    "nameEn": "Guinness Draught",
    "brewery": "Guinness",
    "country": "아일랜드",
    "styleMajor": "스타우트·포터",
    "styleMinor": "Irish Dry Stout",
    "abv": 4.2,
    "ibu": 40,
    "bitterness": 3,
    "sweetness": 1,
    "acidity": 1,
    "aroma": 4,
    "body": 3,
    "carbonation": 1,
    "beginner": 5,
    "adventure": 2,
    "aromaTags": "coffee, roast, cocoa",
    "flavorSummary": "로스팅, 커피, 드라이",
    "foodTags": "굴, 스튜, 버거",
    "occasionTags": "펍, 혼술",
    "natalTags": "차분함, 클래식, 깊이",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 5,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 3,
    "natalAdventure": 2,
    "natalTone": "클래식·차분함"
  },
  {
    "id": "BEER_062",
    "nameKo": "기네스 엑스트라 스타우트",
    "nameEn": "Guinness Extra Stout",
    "brewery": "Guinness",
    "country": "아일랜드",
    "styleMajor": "스타우트·포터",
    "styleMinor": "Export Stout",
    "abv": 5.6,
    "ibu": 45,
    "bitterness": 4,
    "sweetness": 2,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 3,
    "beginner": 4,
    "adventure": 3,
    "aromaTags": "coffee, dark chocolate, roast",
    "flavorSummary": "강한 로스팅, 다크초콜릿",
    "foodTags": "스테이크, 바비큐",
    "occasionTags": "저녁",
    "natalTags": "강인함, 클래식, 집중",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 4,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 3,
    "natalTone": "강인함·집중"
  },
  {
    "id": "BEER_063",
    "nameKo": "올드 라스푸틴",
    "nameEn": "Old Rasputin Russian Imperial Stout",
    "brewery": "North Coast Brewing",
    "country": "미국",
    "styleMajor": "스타우트·포터",
    "styleMinor": "Imperial Stout",
    "abv": 9,
    "ibu": 75,
    "bitterness": 5,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 5,
    "body": 5,
    "carbonation": 2,
    "beginner": 1,
    "adventure": 5,
    "aromaTags": "coffee, dark chocolate, roast",
    "flavorSummary": "강렬한 로스팅, 쌉쌀함",
    "foodTags": "스테이크, 초콜릿 디저트",
    "occasionTags": "혼술, 겨울밤",
    "natalTags": "강렬함, 신비, 깊이",
    "availability": "A",
    "confidence": "높음",
    "natalStability": 2,
    "natalStimulation": 5,
    "natalSensory": 5,
    "natalSocial": 1,
    "natalAdventure": 5,
    "natalTone": "신비·강렬함"
  },
  {
    "id": "BEER_064",
    "nameKo": "사무엘 스미스 오트밀 스타우트",
    "nameEn": "Samuel Smith Oatmeal Stout",
    "brewery": "Samuel Smith",
    "country": "영국",
    "styleMajor": "스타우트·포터",
    "styleMinor": "Oatmeal Stout",
    "abv": 5,
    "ibu": 32,
    "bitterness": 2,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 2,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "coffee, cocoa, oat",
    "flavorSummary": "크리미, 초콜릿, 고소함",
    "foodTags": "디저트, 스튜",
    "occasionTags": "조용한 저녁",
    "natalTags": "포근함, 고전적, 감성적",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 5,
    "natalStimulation": 3,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 3,
    "natalTone": "포근함·감성적"
  },
  {
    "id": "BEER_065",
    "nameKo": "파운더스 KBS",
    "nameEn": "Founders KBS",
    "brewery": "Founders",
    "country": "미국",
    "styleMajor": "스타우트·포터",
    "styleMinor": "Barrel-aged Imperial Stout",
    "abv": 12,
    "ibu": 70,
    "bitterness": 4,
    "sweetness": 5,
    "acidity": 1,
    "aroma": 5,
    "body": 5,
    "carbonation": 1,
    "beginner": 1,
    "adventure": 5,
    "aromaTags": "coffee, chocolate, bourbon, vanilla",
    "flavorSummary": "진한 초콜릿, 커피, 배럴",
    "foodTags": "스테이크, 디저트",
    "occasionTags": "특별한 혼술",
    "natalTags": "강렬함, 사치, 탐구심",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 1,
    "natalStimulation": 5,
    "natalSensory": 5,
    "natalSocial": 1,
    "natalAdventure": 5,
    "natalTone": "사치·탐구"
  },
  {
    "id": "BEER_066",
    "nameKo": "데슈츠 블랙 뷰트 포터",
    "nameEn": "Deschutes Black Butte Porter",
    "brewery": "Deschutes",
    "country": "미국",
    "styleMajor": "스타우트·포터",
    "styleMinor": "American Porter",
    "abv": 5.5,
    "ibu": 30,
    "bitterness": 2,
    "sweetness": 3,
    "acidity": 1,
    "aroma": 5,
    "body": 4,
    "carbonation": 2,
    "beginner": 4,
    "adventure": 2,
    "aromaTags": "chocolate, coffee, roast",
    "flavorSummary": "초콜릿, 커피, 부드러움",
    "foodTags": "버거, 바비큐",
    "occasionTags": "저녁",
    "natalTags": "차분함, 균형, 따뜻함",
    "availability": "C",
    "confidence": "낮음",
    "natalStability": 4,
    "natalStimulation": 3,
    "natalSensory": 4,
    "natalSocial": 3,
    "natalAdventure": 3,
    "natalTone": "따뜻함·차분함"
  },
  {
    "id": "BEER_067",
    "nameKo": "린데만스 크릭",
    "nameEn": "Lindemans Kriek",
    "brewery": "Lindemans",
    "country": "벨기에",
    "styleMajor": "사워·과일 맥주",
    "styleMinor": "Fruit Lambic - Cherry",
    "abv": 3.5,
    "ibu": 12,
    "bitterness": 1,
    "sweetness": 5,
    "acidity": 4,
    "aroma": 5,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 2,
    "aromaTags": "cherry, almond, funk",
    "flavorSummary": "체리, 새콤달콤",
    "foodTags": "디저트, 치즈",
    "occasionTags": "데이트, 디저트",
    "natalTags": "낭만적, 장난기, 화사함",
    "availability": "B",
    "confidence": "높음",
    "natalStability": 3,
    "natalStimulation": 3,
    "natalSensory": 5,
    "natalSocial": 4,
    "natalAdventure": 3,
    "natalTone": "낭만적·화사함"
  },
  {
    "id": "BEER_068",
    "nameKo": "린데만스 프람부아즈",
    "nameEn": "Lindemans Framboise",
    "brewery": "Lindemans",
    "country": "벨기에",
    "styleMajor": "사워·과일 맥주",
    "styleMinor": "Fruit Lambic - Raspberry",
    "abv": 2.5,
    "ibu": 12,
    "bitterness": 1,
    "sweetness": 5,
    "acidity": 4,
    "aroma": 5,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "raspberry, berry, funk",
    "flavorSummary": "라즈베리, 달콤, 산미",
    "foodTags": "디저트, 과일",
    "occasionTags": "데이트",
    "natalTags": "로맨틱, 밝음, 감성적",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 3,
    "natalStimulation": 2,
    "natalSensory": 5,
    "natalSocial": 4,
    "natalAdventure": 3,
    "natalTone": "로맨틱·감성적"
  },
  {
    "id": "BEER_069",
    "nameKo": "린데만스 페슈레즈",
    "nameEn": "Lindemans Pecheresse",
    "brewery": "Lindemans",
    "country": "벨기에",
    "styleMajor": "사워·과일 맥주",
    "styleMinor": "Fruit Lambic - Peach",
    "abv": 2.5,
    "ibu": 10,
    "bitterness": 1,
    "sweetness": 5,
    "acidity": 3,
    "aroma": 5,
    "body": 2,
    "carbonation": 4,
    "beginner": 5,
    "adventure": 1,
    "aromaTags": "peach, fruit, light funk",
    "flavorSummary": "복숭아, 달콤, 산뜻함",
    "foodTags": "디저트, 샐러드",
    "occasionTags": "데이트, 브런치",
    "natalTags": "화사함, 부드러움, 낭만적",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 4,
    "natalStimulation": 2,
    "natalSensory": 5,
    "natalSocial": 4,
    "natalAdventure": 3,
    "natalTone": "부드러움·화사함"
  },
  {
    "id": "BEER_070",
    "nameKo": "린데만스 괴즈",
    "nameEn": "Lindemans Gueuze",
    "brewery": "Lindemans",
    "country": "벨기에",
    "styleMajor": "사워·과일 맥주",
    "styleMinor": "Gueuze",
    "abv": 5,
    "ibu": 12,
    "bitterness": 1,
    "sweetness": 2,
    "acidity": 5,
    "aroma": 5,
    "body": 2,
    "carbonation": 5,
    "beginner": 2,
    "adventure": 5,
    "aromaTags": "lemon, hay, funk, oak",
    "flavorSummary": "강한 산미, 드라이, 펑키",
    "foodTags": "치즈, 해산물",
    "occasionTags": "취향 탐험",
    "natalTags": "모험, 지적 호기심, 독창성",
    "availability": "C",
    "confidence": "중간",
    "natalStability": 1,
    "natalStimulation": 5,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 5,
    "natalTone": "독창적·탐구"
  },
  {
    "id": "BEER_071",
    "nameKo": "듀체스 드 부르고뉴",
    "nameEn": "Duchesse de Bourgogne",
    "brewery": "Verhaeghe",
    "country": "벨기에",
    "styleMajor": "사워·과일 맥주",
    "styleMinor": "Flanders Red Ale",
    "abv": 6.2,
    "ibu": 11,
    "bitterness": 1,
    "sweetness": 4,
    "acidity": 5,
    "aroma": 5,
    "body": 3,
    "carbonation": 3,
    "beginner": 2,
    "adventure": 5,
    "aromaTags": "cherry, balsamic, oak",
    "flavorSummary": "새콤달콤, 와인, 오크",
    "foodTags": "치즈, 오리 제외 육류, 디저트",
    "occasionTags": "특별한 저녁",
    "natalTags": "우아함, 복합성, 신비",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 2,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 5,
    "natalTone": "우아함·신비"
  },
  {
    "id": "BEER_072",
    "nameKo": "로덴바흐 그랑 크뤼",
    "nameEn": "Rodenbach Grand Cru",
    "brewery": "Rodenbach",
    "country": "벨기에",
    "styleMajor": "사워·과일 맥주",
    "styleMinor": "Flanders Red-Brown Ale",
    "abv": 6,
    "ibu": 8,
    "bitterness": 1,
    "sweetness": 3,
    "acidity": 5,
    "aroma": 5,
    "body": 3,
    "carbonation": 3,
    "beginner": 2,
    "adventure": 5,
    "aromaTags": "red fruit, oak, balsamic",
    "flavorSummary": "산미, 붉은과일, 오크",
    "foodTags": "치즈, 스테이크",
    "occasionTags": "특별한 식사",
    "natalTags": "성숙함, 복합성, 예술적",
    "availability": "B",
    "confidence": "중간",
    "natalStability": 2,
    "natalStimulation": 4,
    "natalSensory": 5,
    "natalSocial": 2,
    "natalAdventure": 5,
    "natalTone": "성숙함·예술적"
  }
];
